### ISSUE TITLE
catkin_make errors (on gta-robotics docker image)

### ISSUE THREAD

**Issue by Valtgun** [mjshiggins/ros-examples#3]
I needed to do two changes for catkin_make to compile under gta-robotics docker:
(error: 'vector' does not name a type)
vector<int> compression_params;
to:
std::vector<int> compression_params;

and needed to add:
(error: 'imshow' is not a member of 'cv')
#include <opencv2/highgui/highgui.hpp>

**Comment by mjshiggins** [comment]
Thanks @Valtgun ! Please submit a PR to attach to this issue and I'll accept!
